README.md
Just fixed a heading and added YAML syntax highlighting.
=> Couple of minor README improvements.

README.md, schema.yaml, test/1.1.0/fail-bad-identifier-type-in-root/CITATION.cff, test/1.1.0/fail-bad-identifier-type-in-root/test_fail_bad_identifier.py, test/1.1.0/identifiers-in-reference/CITATION.cff, test/1.1.0/identifiers-in-reference/test_reference_identifiers.py, test/1.1.0/identifiers-in-root/CITATION.cff, test/1.1.0/identifiers-in-root/test_root_identifiers.py
This PR fixes #85 as described in https://github.com/citation-file-format/citation-file-format/issues/85#issuecomment-552432806.
EDIT: Also fixes #72.
=> Add identifiers field

.gitignore, schema-sandbox/data.yml, schema-sandbox/schema.json, schema-sandbox/schema_poc.py
Note the merge target is not `main` but `1.2.0`.
**How to test**
```shell
cd schema-sandbox
```
=> Adds identity definition to the jsonschema schema

CITATION.cff
Add my author info. I'm not sure my contributions are significant, but I appreciate the acknowlegement!
Refs: #116
=> Add sbliven author info

README.md, examples.md
I've attempted some proofreading - not much to report, but still hopefully could be useful for consistency and for better rendering of citations.
=> Polishing markdown for citations (and fixing a minor typo)

CITATION.cff
See https://github.com/citation-file-format/citation-file-format/issues/116
=> CFF update as requested

CONTRIBUTING.md, test/README.md
Refs: #165 
Described how the tests are organised and how to run them locally.
@jspaaks this is my understanding of how this works by looking at the current state of the testing code - I didn't look at the history and I may be wrong. Also, formulations may not follow the style used in other parts of instructions - I will be happy to correct and force-push my branch following the suggestions.
=> Documenting testing framework

CITATION.cff
=> Updates author list as requested

CITATION.cff
Adding my details as asked in #116. Thank you!
=> Update author list as requested

schema.json
Fix #226
- Add a definition for `version`
- Reference definition in `version` fields
Check for test failures, otherwise do it live.
=> Deduplicate version field to fix #226

examples/1.1.0/key-complete/CITATION.cff, examples/1.2.0/pass/key-complete/CITATION.cff
Refs: none
I didn't raise an issue for this, just fixed it!
I spotted that the key complete example `1.2.0` file was missing `alias` from `Person` and `identifiers` from the top-level and the `Reference`. This fixes that and I've checked that it validates against the `1.2.0` schema.
I then noticed that these fields were also missing from the `1.1.0` key complete example, so I fixed that too.
Hopefully a trivial check. I had to add 9 instances of `alias` and two of `identifiers`. Some dangling whitespace got fixed by my editor but I put that in a separate commit to avoid obfuscating the real changes.
=> Fix complete cff

examples/1.2.0/pass/key-complete/CITATION.cff
None!
Added a key complete `Reference` object to the top-level `preferred-citation` field.
I just copied the `Reference` that was already there, so hopefully it's OK!
=> Add `preferred-citation` to the 1.2.0 complete example.

schema-guide.md
Refs: #206
Includes: #261, #262, #266
- Copy edit some wording
- Rename and edit ex-"transitive credit" section (see also #267)
- Skew credit redirection section slightly towards better practice (of citing both software and paper rather than just paper)
- Fix linting error in schema.json
- Look at the changes in `schema-guide.md`
=> Optimize intro sections in schema guide

schema-guide.md
- fix #251
- Replaces all *required* values in "top-level" definitions (ie., `definitions.** without further subkeys") to n/a
- Fix some un-code-tagged places with "false"
- Sleep over this
- Look at schema-guide.md
=> Replace required defs with N/A where applicable

schema-guide.md
Refs: -
- Fix `definitions.url`: fix description and remove unneeded examples
- Look at schema-guide.md
=> Fix description of url and remove unneeded examples

schema-guide.md
Refs: #240
- Fix typos
- Fix some minor wording
- Add links where I deemed it useful
Note: all changes for one thing should be encapsulated in one commit, so as to make thing easily revertable.
- Look at `schema-guide.md`
- Decide if all added links are useful and necessary
=> Fix typos and add links

schema-guide.md
Yet another alternative to PR #279 PR #280
Attempt at documenting `identifiers` in an understandable way.
See section [`definitions.identifier`](https://github.com/citation-file-format/citation-file-format/blob/278-identifiers-another-one/schema-guide.md#definitionsidentifier) in file `schema-guide.md` on this branch.
=> Attempt 3 to define 'identifier' complete and understandable

schema-guide.md
:warning: **This PR has an alternative "implementation" in PR #279, merge only one!**
Fixes #278
- Try to define identifier less confusingly
- Add requiredness info, etc.
- Decide whether this is better than what's currently in 1.2.0.
=> Attempt 2 to define 'identifier' complete and understandable

CITATION.cff
Refs: #284
This PR adds `references` to the CITATION.cff file at the repo root.
- see if the validation passes
- check the references
- we could still also lint this with yamllint
- 2nd reference (Druskat 2017) is internally a bit inconsistent
- 4th reference (Hufflen 2006) there is more information we could add if you follow the url
=> Added references to project's CITATION.cff

.github/ISSUE_TEMPLATE/30_validation_issue.md
Fix #291
- Add an issue template for users who have issues with validation
- Look at the new issue template file
=> Add issue template for validation requests

.github/ISSUE_TEMPLATE/20_feature.md, .github/ISSUE_TEMPLATE/40_tooling.md, README.md
Fix: #292
- Add links to labeled issues to README
- Add issue temlpates for tooling ideas
- Change "feature request" template to be about schema changes only
- Look at README.md
- Look at the new and the changed issue template files
=> Optimize issue templates for different issue types

CITATION.cff
Refs: #300
- changed `doi` to `identifiers` refs #300;
- corrected instances of `conference` and of `authors`;
- converted `date-released` to `string` type.
- `identifiers[1].value` is still a placeholder
- Look at the diff
- Run the validator or use https://onlineyamltools.com/convert-yaml-to-json and https://jsonschemalint.com/#!/version/draft-07/markup/json
=> Corrected some citation metadata, prepared citation file for release with placeholder

.github/PULL_REQUEST_TEMPLATE.md
Refs: -
- Fix typo and wording in PR template
- Optimize review checklist:
- Transform into actual review checklist
- Move instructions to contributors to HTML comments
```bash
Look at PR template
```
=> Optimize review checklist in PR template

README.md
Fix #215
- Testing badge reports only from `main`
- Testing badge points to testing results in `main`
- Look at the README.md to see whether the badge is correctly reporting and linking
=> Fix #215: Let testing badge report main only

CHANGELOG.md, CITATION.cff, schema.json
Fixes #323
Fixed regexp pattern for `isbn`, per discussion in the bug ticket
=> Corrected ISBN10 regex

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md
Fixes #324
- Adds documentation about which branches to use when to:
- README (very basic info only for the case where people do *not* use `main`)
- Contribution guidelines
- PR template (checkbox to check against correct branch, see below)
- Also removes the `**Instructions to review the pull request**` section from the PR template, as this seems to be a missed leftover from when it was renamed *Review checklist*
=> Implement new branching model

CHANGELOG.md, examples/1.2.0/pass/isbn10/CITATION.cff, examples/1.2.0/pass/isbn10/README.md
Refs: #336, PR #335
Added a test for ISBN10 strings
=> added a test for isbn10 strings

README.md
Adds a corporate author example. See [discussion](https://github.com/infoqualitylab/Empirical-Retraction-Lit/pull/1)
=> add example corporate author

README.md
Refs: -
- Adds a section on creationg CFF files to README
- Makes the line with the link to the schema guide bold for better visibility.
=> Add creation section to REDAME

tool-catalogue.md
Refs:  fixes #350
This is a simple draft of how a tooling catalogue could be realised.  It incorporates the ideas of #350 and uses @hainesr's library `ruby-cff` as an example for multi-purpose CFF tools.  This Pull Request is intended for discussion on how this approach could help to improve the overview about CFF related technology.
```bash
pytest
```
=> [Bugfix] Fix #350 (#3)

schema-guide.md
Refs: #447
Fixed a few minor link problems to close #447
```bash
pytest
```
=> fixed some links

.github/workflows/cffconvert.yml, .github/workflows/check-links.yml, .github/workflows/linting.yml, .github/workflows/testing.yml
Refs:
- #508
- Bumped `actions/checkout` to v4
- Bumped `actions/setup-python` to v5
```bash
pytest
```
=> bump actions versions

README.dev.md
Refs: #510
Updated _Testing_ section in `README.dev.md` with changes resulting from now-merged PR #507.
```bash
pytest
```
=> updated testing section in `README.dev.md`

.github/workflows/check-links.yml
Refs:
- #447
We currently don't have a way to trigger the link checker manually, so I pulled in the recently updated link checker workflow from development branch. Hence the target for this PR is `main` branch.
```bash
pytest
```
=> Pull in link checker from development branch

schema-guide.md
Refs:
- #486
updated list of license identifiers in `schema-guide.md` so it's in sync with the information from `schema.json`
```bash
pytest
```
=> updated list of license identifiers in schema-guide.md

schema-guide.md, schema.json
Refs: #327
- Adapt wording in schema and schema guide to better express the intention of `references`
- Additionally, improve wording in documentation of `preferred-citation` to better express the intention.
```bash
pytest
```
=> Improve references docs

.github/workflows/testing.yml, examples/README.md
This PR updates the used actions in the CI and adds Python versions 3.12 and 3.13.
Furthermore it fixes a small typo.
```bash
pytest -v
```
=> Update test actions and add support for Python 3.12 and 3.13
