.gitignore
schema.yaml
test/1.1.0/doi-with-slash/CITATION.cff
test/1.1.0/doi-with-slash/test_doi_with_slash.py

This PR fixes #92.
Cherry-picked https://github.com/citation-file-format/schema/commit/c40ccac00896aa8532b76b46e6e5df709965bd13 by @sbliven to keep commit history and commit ownership.

Allow forward slash in DOI

---

README.md

Created using https://github.com/ekalinin/github-markdown-toc.
Now it's placed just above "Example". Let me know if you prefer it placed below and I can adjust.

add TOC for README; closes #100

---

README.md
schema.yaml
test/1.1.0/alias-minimal/CITATION.cff
test/1.1.0/alias-minimal/test_alias_minimal.py

- added optional key 'alias' to author schema
- updated the docs accordingly
- fixes #93
Furthermore,
- made ``family-names`` not required
- made ``given-names`` not required
- updated the readme accordingly.
This last change basically gives CFF writers more freedom and a bit more responsibility to strive for good data, but the benefit is that people can now write valid files when:
- an author is known only by an alias
- an author is known only by their family name

added 'alias'

---

schema-sandbox/data.yml
schema-sandbox/schema.json

This PR adds url based optional keys `license-url`, `repository`, `repository-code`, `repository-artefact`,  `url`
Note the merge target is not `main` but `1.2.0`.
**How to test**
```shell
cd schema-sandbox
```

Adds URL based optional keys in root document

---

schema-sandbox/schema.json

Merge target is `1.2.0`
Refs #126 
Includes: PR #124
Can be marked _ready for review_ after merge of PR #124
This PR adds validation of `identifiers` array members, using validation regular expressions from `#/definitions/url` and `#/definitions/doi`.
`identifiers` of `type` `other` and `swh` remain unvalidated for the moment.

Adds validation of identifiers when type is url or doi

---

schema-sandbox/schema.json

Refs #127
Merge target `1.2.0`
Inlcludes PR #124
This PR adds a bit more validation for language codes in the key `languages`. I tested the regular expression on regex101.com using all the keys we had previously, they are all recognized

language code validation

---

README.md

This PR follows the comment by @jspaaks in #117 and adds CI badge.
You can see the rendered version of README in my fork here: https://github.com/alex-konovalov/citation-file-format/tree/add-gh-badge
I submitted it to 1.2.0 branch, but the URLs for the badge are resolved without specifying branch - so there will be no need to update them after 1.2.0 will be merged into main (I hope I got the workflow right - if I need to submit this to main instead, please let me know and I will rebase!).

Add GitHub actions badge

---

schema.json

Refs: n/a
- Introduce a `commit` definition without a regex (`commit` is meant to take any revision or commit identifiers from any VCS, not just git SHA1 hashes).
- Reuse definition in two fields in schema
```bash
```

Remove commit regex

---

data.yml
schema.json

This PR is against `1.2.0`!
Refs: 
- fix #128 
- Doesn't supply a fix for #105
- Move license enums to "private" definition `#/definitions/_license-enum`
- Re-define `#/definitions/license` to be `oneOf` `_license_enum` or an array pf `_license-enum`.
- Add test data to test both cases
```bash
```

Implement multi-licensed items

---

schema.json

Fixes #176
- Add the `term` field (string) to the reference object
- Add a description for term
```bash
```

Fix #176: Add 'term' to reference

---

schema.json

- Fix #185
- Add default values for `message` and `type` as per #185.
```bash
```

Add default values for type and message

---

schema.json

Refs: None
- Requires a `minLength` of 1 for all string values, which blocks uninformative empty string fields (`""`).

Disallow empty strings as values

---

schema.json

Fix #179
- Add a definition for unqualified SWH identifiers
- Separate the `swh` and `other` enums in the `identifier` definition
- Let `swh` use the new definition
- Note that the field takes unqualified identifiers only.
- Check if we want to support qualified identifiers as well (cf. https://docs.softwareheritage.org/devel/swh-model/persistent-identifiers.html#qualifiers)
```bash
```

Add stricter validation for SWH identifiers

---

schema.json

Fix #198
- Fix structure of `schema.json` to be valid JSON again and merge duplicate keys into the correct version
```bash
```

Fix structure of schema.json to be valid JSON again

---

schema.json
tests/1.2.0/poc/CITATION.cff

Fix #189
- Remove `version` and `date-released` from the `required` array of the root properties object, thereby making them optional
```bash
python3 tests/schema_poc.py -d tests/1.2.0/poc/CITATION.cff -s schema.json  # <- should be quiet
```bash

Make version, date-released root fields optional

---

schema.json
tests/1.2.0/poc/CITATION.cff

Fix #181
- Adds an optional field `description` to all identifier properties
- Define `identifier-description` object
- Add test data for new field
```bash
python3 tests/schema_poc.py -d tests/1.2.0/poc/CITATION.cff -s schema.json  # <- should be quiet
```bash

Add optional `description` property to identifiers

---

tests/1.2.0/poc/CITATION.cff
tests/schema_poc.py

This PR implements option 3. in https://github.com/citation-file-format/citation-file-format/issues/202#issuecomment-855801103 for our use case, validating test instances of `CITATION.cff` during CI.
This change doesn't break API, and is one way to solve this for Python clients using the `jsonschema` package.
Refs: #202
- Keep using YAML timestamp data for dates in CFF
- Change the way that YAML is being deserialized for validation in tests
(deserialize all timestamps as strings)
- Activate format checks in Python script (cf. [example for fail](https://github.com/citation-file-format/citation-file-format/runs/2731942670#step:7:26))
- Add some test data
- Note that this also allows for correctly formatted strings as …

Fix #202 without breaking API

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

- Uses DOIs for older releases, as tags on GitHub aren't available
for diffing for all releases (going across repos).
- Fix (partly) #221
- `CHANGELOG.md` will still need to be updated for `1.2.0`
- Add `CHANGELOG.md` according to https://keepachangelog.com/en/1.0.0/

Add changelog

---

schema.json

Fixes #235.
Refs: #235
(For autoclosure of issues when PR is merged use `Fixes #<issue-number>` syntax)
Escapes the bare `-` in the ISBN regex.
Trivial change is on line 1264 of the schema.

Fix trailing `-` warning in schema.

---

schema-guide.md

Adds the changes originally included in #239 but not merged yet.
Refs: #239
- Optimize description for `repository-artifact` and `repository-code`  
- Deviates from the original suggestion in https://github.com/citation-file-format/citation-file-format/pull/239#discussion_r675969245, as datasets can also live in code repositories, but not in artifact repos
- Remove quotes around enum values in schema guide: `software`and `dataset

Incorporate smaller changes from #239

---

schema-guide.md
schema.json

Refs: #240
Includes: PR #250 
This PR adds the same layout for subkeys of entity and person as we already have for the other keys, i.e. like so https://github.com/citation-file-format/citation-file-format/issues/240#issuecomment-886170125.
Look how `schema-guide.md` from this branch is rendered

same layout everywhere in schema-guide.md

---

schema-guide.md
schema.json

Refs: #206
- Add more key descriptions to the schema guide
Note to @jspaaks: 1b3b980c4da6bdb3e23c13eb19cd4f52cfb7fa9a changes the way that arrays are formatted in usage examples. We can discuss whether the formatting with linebreak is preferrable in case this was deliberate, e.g., to stress the difference between a single object and an array, but I thought this takes too much space (*de gustibus non est disputandem*).
- Look at the changes in `schema-guide.md` & `schema.json`

Schema guide descriptions for root-level keys `preferred-citation` and `references`

---

schema-guide.md

Refs: #206
Includes: #256 
- Despite its title, also adds all available fields to the first entity definition example
- Check if this all makes sense (i.e., look at `schema-guide.md`)

Add definitions for `definitions.person`

---

schema-guide.md

Refs: #240
- Replaces all instances of 'field' and 'property' etc. with 'key'/'keys'
- Merge.

Fix 'fields'/'keys' wording

---

schema-guide.md

Refs: #288
- This PR makes the nested list items explaining the various flavors of identifier collapsible.
- Also in this PR: I removed trailing whitespace throughout `schema-guide.md`
- Look at this branch's [`schema-guide.md#definitions.identifier`](https://github.com/citation-file-format/citation-file-format/blob/288-collapsible-list-items/schema-guide.md#definitionsidentifier)

Made identifiers objects description collapsible list items

---

schema.json

- See https://github.com/citation-file-format/citation-file-format/issues/190#issuecomment-893512188
Refs: #190, https://github.com/citation-file-format/citation-file-format.github.io/pull/31
- Appends the `.json` extension to the schema `$id`
1. Go to https://www.jsonschemavalidator.net/
2. For the schema, use the one from this PR
```json
{
"$ref": "https://raw.githubusercontent.com/citation-file-format/citation-file-format/e5c605351e31e2c681ce1dbbbeb8ec00c6944a96/schema.json"
}
```
3. Play around with valid/invalid "CFF-JSON", e.g.:
```json
{
"cff-version": "1.3.0"
}
```
```json
{
"authors": [{
"alias": "author"
}],
"cff-version": "1.2.0",
"message": "None",
"title": …
```

Fix schema $id

---

CONTRIBUTING.md

- Fix #234
- Fix #169
- Optimize contribution guidelines (#234)
- Describe workflow as an enumerated list based on GitHub flow (#169)
- Remove mentions of how things are done in other repos
- Add note about what to do when people want to contribute to another
repo
- Slim down FAQ
- Mention branch to branch off of (#169)
- Read though CONTRIBUTING.md
- Discuss whether we should lock down `main` (I'm personally :+1:)

Optimize contribution guidelines

---

.github/PULL_REQUEST_TEMPLATE.md
schema-guide.md

N/A
Fixed the indentation of a closing code mark `` ``` ``
Search for the stray `` ``` `` in the [initial rendered text](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md). In my [fork](https://github.com/pothitos/citation-file-format/blob/patch-1/schema-guide.md) it has disappeared.
```bash
pytest
```

Fix typo and closing code block mark indentation

---

CITATION.cff

Fixes #318
- Duplicates the value from `identifiers[1]` in the `doi` field to achieve rendering on GitHub
- Check CFF file
```bash
python examples/validator.py -s schema.json -d CITATION.cff
```

Duplicate identifiers[1] in doi field

---

schema-guide.md

Fixes #322
- Lint examples for string quoting
- Explain the basics of YAML string quoting in first guide section
- Fix a few bad string examples (`"<string1>" <string2>`), which apparently weren't caught by linting
```bash
pytest
```

Explain YAML string quoting, and lint examples

---

CHANGELOG.md
README.md
schema-guide.md

I get new records added to my ORCID account every now and then, because examples and templates include my real ORCID 🙄. This is also entirely my fault.
- Replace my ORCID in README and schema guide with the example valid ORCID given at https://orcid.org/1234-5678-9101-1121.
```bash
git checkout remove-real-orcid
pytest
```

Remove real orcid

---

schema.json

Refs: N/A
This PR updates some minor schema parts, e.g.
1. I replaced `anyOf` with `oneOf`, because we don't have cases where we want to match more than 1 subschema simultaneously
2. I replaced singular value `enum`s with just a `const`
3. I replaced `definitions` with `$defs` as per the recommended practice (`$defs` was introduced in JSONSchema draft 2019-09 BTW, and we need draft 2019-09 if we want to have extensible subschemas, for example an item in `contributors` that extends `person` in PR #463)
```bash
git clone …
```

Minor schema updates

---

examples/1.2.0/fail/nonunique-authors/CITATION.cff
examples/1.2.0/fail/nonunique-contact/CITATION.cff
examples/1.2.0/fail/nonunique-contributors/CITATION.cff
examples/1.3.0/pass/nonunique-authors/CITATION.cff
examples/1.3.0/pass/nonunique-contact/CITATION.cff
examples/1.3.0/pass/nonunique-contributors/CITATION.cff
schema.json

Refs:
- #472
This PR removes the `uniqueItems` requirement on all usages of the `person` definition:
1. `references.authors`
2. `references.contact`
3. `references.editors`
4. `references.editors-series`
5. `references.recipients`
6. `references.senders`
7. `references.translators`
8. `authors`
9. `contact`
10. `contributors`
TODO 
1. ~~Needs tests~~ _Added_
2. ~~Check guide text~~ _Doesn't mention uniquess AFAICT_
```bash
pip install …
```

Remove uniqueness requirement on authors and other persons

---

examples/1.2.0/fail/entity-author-with-affiliation/CITATION.cff
examples/1.3.0/pass/entity-author-with-affiliation/CITATION.cff
schema-guide.md
schema.json

Refs:
- #479
This PR adds `affiliation` to all usages of the `entity` definition. I added 2 tests (for `authors`), one for cff 1.2.0 that should fail, and one for 1.3.0 that should pass.
```bash
pytest
```

Add affiliation for entities

---

schema-guide.md

Refs:
- N/A
This PR adds an entry for `strictish-string` in the index of `$defs` in `schema-guide.md`.
```bash
pytest
```

Add strictish-string in index of definitions

---

schema-guide.md

Fixes #477
(For autoclosure of issues when PR is merged use `Fixes #<issue-number>` syntax)
- Adds a regex101 link to definition of strictish string
```bash
pytest
```

Fix #477: Add regex101 link for strictish-string

---

CHANGELOG.md
schema-guide.md
schema.json

Refs: #347
- Implements the decision to let `reference.number` to be the suitable field for providing article numbers/IDs by adapting documentation.
```bash
git checkout 347-article-number
pytest
```

Adapt documentation for `reference.number` to include article numbers/identifiers

---

CHANGELOG.md
CODE_OF_CONDUCT.md

Refs: https://github.com/citation-file-format/governance/issues/2
- Change code of conduct document to make the CoC Committee the new point-of-contact
- Add section listing the committee members with email addresses (as `mailto:` links).

Update Code of Conduct contacts
